<a href="https://colab.research.google.com/github/KoushaniBiswas/Incarnation-/blob/master/python_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello world")

Hello world


In [2]:
x = 2
y = x+3
print(y)

5


import sample csv files to google **colab** **bold text**

---



---



In [3]:
from google.colab import files
files.upload()

Saving inflammation-01.csv to inflammation-01.csv
Saving inflammation-02.csv to inflammation-02.csv
Saving inflammation-03.csv to inflammation-03.csv
Saving inflammation-04.csv to inflammation-04.csv
Saving inflammation-05.csv to inflammation-05.csv
Saving inflammation-06.csv to inflammation-06.csv
Saving inflammation-07.csv to inflammation-07.csv
Saving inflammation-08.csv to inflammation-08.csv
Saving inflammation-09.csv to inflammation-09.csv
Saving inflammation-10.csv to inflammation-10.csv
Saving inflammation-11.csv to inflammation-11.csv
Saving inflammation-12.csv to inflammation-12.csv
Saving small-01.csv to small-01.csv
Saving small-02.csv to small-02.csv
Saving small-03.csv to small-03.csv


{'inflammation-01.csv': b'0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0\n0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1\n0,1,1,3,3,2,6,2,5,9,5,7,4,5,4,15,5,11,9,10,19,14,12,17,7,12,11,7,4,2,10,5,4,2,2,3,2,2,1,1\n0,0,2,0,4,2,2,1,6,7,10,7,9,13,8,8,15,10,10,7,17,4,4,7,6,15,6,4,9,11,3,5,6,3,3,4,2,3,2,1\n0,1,1,3,3,1,3,5,2,4,4,7,6,5,3,10,8,10,6,17,9,14,9,7,13,9,12,6,7,7,9,6,3,2,2,4,2,0,1,1\n0,0,1,2,2,4,2,1,6,4,7,6,6,9,9,15,4,16,18,12,12,5,18,9,5,3,10,3,12,7,8,4,7,3,5,4,4,3,2,1\n0,0,2,2,4,2,2,5,5,8,6,5,11,9,4,13,5,12,10,6,9,17,15,8,9,3,13,7,8,2,8,8,4,2,3,5,4,1,1,1\n0,0,1,2,3,1,2,3,5,3,7,8,8,5,10,9,15,11,18,19,20,8,5,13,15,10,6,10,6,7,4,9,3,5,2,5,3,2,2,1\n0,0,0,3,1,5,6,5,5,8,2,4,11,12,10,11,9,10,17,11,6,16,12,6,8,14,6,13,10,11,4,6,4,7,6,3,2,1,0,0\n0,1,1,2,1,3,5,3,5,8,6,8,12,5,13,6,13,8,16,8,18,15,16,14,12,7,3,8,9,11,2,5,4,5,1,4,1,2,0,0\n0,1,0,0,4,3,3,5,5,4,5,8,7,10,13,3,7,13,15,18,8,15,15,16,11,14,12,4,10,10,4,3,4

In [4]:
3+5*4

23

Importing Numpy 

---



In [5]:
import numpy

importing the file we want to analyze


---



---



In [6]:
numpy.loadtxt(fname='inflammation-01.scv', delimiter=',')

OSError: ignored

In [7]:
from google.colab import files
files.upload()


Saving inflammation-01.csv to inflammation-01 (1).csv


{'inflammation-01.csv': b'0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0\n0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1\n0,1,1,3,3,2,6,2,5,9,5,7,4,5,4,15,5,11,9,10,19,14,12,17,7,12,11,7,4,2,10,5,4,2,2,3,2,2,1,1\n0,0,2,0,4,2,2,1,6,7,10,7,9,13,8,8,15,10,10,7,17,4,4,7,6,15,6,4,9,11,3,5,6,3,3,4,2,3,2,1\n0,1,1,3,3,1,3,5,2,4,4,7,6,5,3,10,8,10,6,17,9,14,9,7,13,9,12,6,7,7,9,6,3,2,2,4,2,0,1,1\n0,0,1,2,2,4,2,1,6,4,7,6,6,9,9,15,4,16,18,12,12,5,18,9,5,3,10,3,12,7,8,4,7,3,5,4,4,3,2,1\n0,0,2,2,4,2,2,5,5,8,6,5,11,9,4,13,5,12,10,6,9,17,15,8,9,3,13,7,8,2,8,8,4,2,3,5,4,1,1,1\n0,0,1,2,3,1,2,3,5,3,7,8,8,5,10,9,15,11,18,19,20,8,5,13,15,10,6,10,6,7,4,9,3,5,2,5,3,2,2,1\n0,0,0,3,1,5,6,5,5,8,2,4,11,12,10,11,9,10,17,11,6,16,12,6,8,14,6,13,10,11,4,6,4,7,6,3,2,1,0,0\n0,1,1,2,1,3,5,3,5,8,6,8,12,5,13,6,13,8,16,8,18,15,16,14,12,7,3,8,9,11,2,5,4,5,1,4,1,2,0,0\n0,1,0,0,4,3,3,5,5,4,5,8,7,10,13,3,7,13,15,18,8,15,15,16,11,14,12,4,10,10,4,3,4

In [8]:
import numpy as np


In [9]:
np.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [ ]:
The expression numpy.loadtxt(...) is a function call that asks Python to run the function loadtxt which belongs to the numpy library.

numpy.loadtxt has two parameters: the name of the file we want to read and the delimiter that separates values on a line

RETURNING AND SAVE THE RETURNED DATA

In [10]:
data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')


PRINT THE VARIABLE'S VALUES

In [11]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


ASKING WHAT TYPE OF DATA IS USED

In [12]:
print(type(data))

<class 'numpy.ndarray'>


the result tells us about the n dimensional array 

TO UNDERSTAND WHAT IS INSIDE THE ARRAY

In [13]:
print(daa.dtype)

NameError: ignored

In [14]:
print(data.dtype)

float64


TO KNOW THE STRUCTURE OF THE ARRAY - NO OF COLUMNS AND NO OF ROWS

In [15]:
print(data.shape)

(60, 40)


GETTING SINGLE NUMBER FROM THE ARRAY

In [17]:
print('first value in data:', data[0,0])

first value in data: 0.0


In [18]:
print('middle value in data:', data[30,20])

middle value in data: 13.0


**SLICING DATA**

---



---



---



SELECTING X NO.OF COLUMNS FOR Y NUMBER OF ROWS

In [19]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


slice 0:4means - start at index 0 and go up to but not including index 4

if we use : the slice includes everything

In [20]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


The above example selects rows 0 through 2 and columns 36 through to the end of the array

---



ASKING NUMPY TO COMPUTE DATA;'S MEAN VALUE

In [21]:
print(numpy.mean(data))

6.14875


mean id a functon that takes an array as an argument - argument is when a value is assigned to a paramenter when it runs

THREE OTHER NUMPY FUNCTION TO GET DESCRIPTIVE VALUES ABOUT THE DATA SITE

MAX VAL, MIN VAL, STDVAL

In [23]:
maxval, minval, stdval = numpy.max(data), numpy.min(data), numpy.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


LOOKING AT VARIATIONS IN STATISTICAL VALUES 

---



CREATING A NEW TEMPORARY ARRAY OF THE DATA WE WANT AND THEN ASK IT TO CALCULATE FOR US

---



---



In [25]:
patient_0 = data[0, :]
#0 on the first axis(rows), everything on the second (column)
print('maximum inflammation for patient 0:', numpy.max(patient_0))

maximum inflammation for patient 0: 18.0


In [30]:
#combining the selection and calling the function
print('maximum inflammation for patient 2:', numpy.max(data[2,:]))

maximum inflammation for patient 2: 19.0


In [32]:
print('maximum inflammation for patient 4:', numpy.max(data[4,:]))

maximum inflammation for patient 4: 17.0


MAX FOR EACH PATIENT : NUPY.MAX 
AVERAGE PER DAY : NUMPY.MEAN

In [33]:
print(numpy.mean(data, axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [34]:
#asking the above array what shape it is
print(numpy.mean(data, axis=0).shape)

(40,)


the above expression tells us we have an N*1 vector - the avg inflammation per day for all patients 


In [35]:
print(numpy.mean(data, axis=1))

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]


SLICING STRINGS

---



---



In [36]:
#section of an array is called a slice
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [37]:
element = 'oxygen'
print('elemen 4:', element[0:4])

elemen 4: oxyg


In [38]:
element = 'oxygen'
print('element4:', element[4:0])

element4: 


In [39]:
element = 'oxygen'
print('element:', element[:])

element: oxygen


In [43]:
element = 'oxygen'
print('negative element:', element[-1])

negative element: n


STACKING ARRAYS

In [44]:
import numpy  
A = numpy.array([[1,2,2], [4,5,6], [7,8,9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 2]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 2 1 2 2]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 2]
 [4 5 6]
 [7 8 9]
 [1 2 2]
 [4 5 6]
 [7 8 9]]


In [45]:
import numpy  
A = numpy.array([[1,2,2], [4,5,6], [7,8,9]])
print('A = ')
print(A)

element = A
print(element[3:2])

A = 
[[1 2 2]
 [4 5 6]
 [7 8 9]]
[]


In [50]:
# slicing the first and last columns of A and stacking them into 3*2array
import numpy  
A = numpy.array([[1,2,2], [4,5,6], [7,8,9]])
print('A = ')
print(A)
A =  numpy.hstack((A[:, :1], A[:, -1]))
print('A = ')
print(A)


A = 
[[1 2 2]
 [4 5 6]
 [7 8 9]]


ValueError: ignored

In [55]:
#numpy.diff()  function takes an array and returns the differences between two successive value
patient2_week1 = data[3,:7]
print(patient2_week1)

[0. 0. 2. 0. 4. 2. 2.]


In [52]:
numpy.diff(patient3_week1)

array([ 0.,  2., -2.,  4., -2.,  0.])

In [56]:
numpy.diff(patient2_week1)

array([ 0.,  2., -2.,  4., -2.,  0.])

In [ ]:
#to upload files to the colab
from google.colab import files
files.upload()